### Data analysis and EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('survey.csv')
df.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [3]:
df.shape

(1259, 27)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   object
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   object
 3   Country                    1259 non-null   object
 4   state                      744 non-null    object
 5   self_employed              1241 non-null   object
 6   family_history             1259 non-null   object
 7   treatment                  1259 non-null   object
 8   work_interfere             995 non-null    object
 9   no_employees               1259 non-null   object
 10  remote_work                1259 non-null   object
 11  tech_company               1259 non-null   object
 12  benefits                   1259 non-null   object
 13  care_options               1259 non-null   object
 14  wellness_program           1259 non-null   object
 15  seek_help                  1259 non-null   object
 16  anonymity                  1259 non-null   object
 17  leave                      1259 non-null   object
 18  mental_health_consequence  1259 non-null   object
 19  phys_health_consequence    1259 non-null   object
 20  coworkers                  1259 non-null   object
 21  supervisor                 1259 non-null   object
 22  mental_health_interview    1259 non-null   object
 23  phys_health_interview      1259 non-null   object
 24  mental_vs_physical         1259 non-null   object
 25  obs_consequence            1259 non-null   object
 26  comments                   164 non-null    object
dtypes: int64(1), object(26)
memory usage: 265.7+ KB

In [5]:
df.describe()

                Age
count  1.259000e+03
mean   7.942815e+07
std    2.818299e+09
min   -1.726000e+03
25%    2.700000e+01
50%    3.100000e+01
75%    3.600000e+01
max    1.000000e+11

### cleaning age column: 
convert outliers in age column to null values, then take count of null values and then delete null rows compltely.

In [6]:
df.loc[(df['Age'] < 18) | (df['Age'] > 100), 'Age'] = np.nan

In [7]:
df['Age'].isnull().sum() #8 null values

np.int64(8)

In [8]:
df.dropna(subset=['Age'], inplace=True) #deleting null value rows.

In [9]:
df['Age'].isnull().sum() #0 null values

np.int64(0)

### cleaning gender column

In [10]:
df['Gender'].value_counts()

Gender
Male                                              612
male                                              204
Female                                            121
M                                                 116
female                                             62
F                                                  38
m                                                  34
f                                                  15
Make                                                4
Woman                                               3
Male                                                3
Female                                              2
Cis Male                                            2
Man                                                 2
Female (trans)                                      2
something kinda male?                               1
Trans-female                                        1
Cis Female                                          1
Male-ish                                            1
maile                                               1
queer/she/they                                      1
Male (CIS)                                          1
woman                                               1
Nah                                                 1
fluid                                               1
Enby                                                1
Genderqueer                                         1
non-binary                                          1
Femake                                              1
Mal                                                 1
cis-female/femme                                    1
Agender                                             1
Androgyne                                           1
male leaning androgynous                            1
Guy (-ish) ^_^                                      1
Trans woman                                         1
msle                                                1
Neuter                                              1
queer                                               1
Female (cis)                                        1
Mail                                                1
cis male                                            1
Malr                                                1
femail                                              1
Cis Man                                             1
ostensibly male, unsure what that really means      1
Name: count, dtype: int64

In [11]:
#convert gender column to lowercase
df['Gender'] = df['Gender'].str.lower()

# 2 classify Male, Female, Other to 3 different group.
def clean_gender(val):
    if 'm' in val and 'fe' not in val and 'trans' not in val and 'something' not in val:
        return 'Male'
    elif 'f' in val and 'trans' not in val:
        return 'Female'
    else:
        return 'Other/Non-Binary'    
df['Gender'] = df['Gender'].apply(clean_gender)


# 3.count gender column value
df['Gender'].value_counts()

Gender
Male                992
Female              244
Other/Non-Binary     15
Name: count, dtype: int64